### PR TITLE
Resizeable boxes

### LINKED ISSUE #347: Adjustable Bounding Boxes
- [x] Check if ~~d3~~ interact.js conveniently supports adjustments
- [x] Connect svg bounding boxes with interact.js
- [x] Add possibility to adjust bounding boxes
- [x] Properly store the new data
- [ ] Notify back-end about the update
- [ ] Trigger OCR Processing on the single slice! (backend API required)

### PR DESCRIPTION
**Pull request by lgalke**
Fixes #347

Back-end and OCR component functionality still have to be tested.

### CODE REVIEW

**Comment by lgalke** [comment]
We need to call the back-end service with an optional parameter for the entry_id and filter out the 'OBSOLETE' entries.

**Comment by lgalke** [comment]
`ERROR in src/app/inspectors/display/display.component.ts(246,55): error TS2339: Property 'addDeleteMode' does not exist on type 'DisplayComponent'.`

**Comment by chah3d** [comment]
There is still an issue regarding the Filters, if different filters are set only the first is applied.

**Comment by lgalke** [comment]
Let me know when it is safe to merge in this PR. It could be also helpful to tackle #401 .

>There is still an issue regarding the Filters, if different filters are set only the first is applied.

This is strange, is it any different in master though?

**Pull request merged**
