### PR TITLE
Resizeable boxes

### PR DESCRIPTION
**Pull request by chah3d**
**Summary**

This PR fixes/implements the following **bugs/features**

* [x] Bugfix: Interactjs initialization moved to router service.
  To reset associated interactjs function, the page has to be reloaded completely, to prevent multiple initializations of these function stack in a workflow along the router pathways between different scans, interactjs is only initalized on first Display Component initialization.
* [x] Feature 1: Edit Mode for bounding boxes

selection_009

selection_010

* [x] Feature 2: Zoom on selected entry
selection_012
selection_011
selection_013

### CODE REVIEW

**Comment by lgalke** [comment]
Deployed to `dev`

**Comment by lgalke** [comment]
@LauraErhard could you please try this feature on dev explicitly? That'd be great! I'd hold it back from production until then.

**Comment by LauraErhard** [comment]
I just did my first tests and I get different errors while trying to delete boxes:
`[scan-inspector][Error] Error while deleting Entry: Http failure response for https://locdb.bib.uni-mannheim.de/locdb-dev/bibliographicEntries/5bf42f664b39d61a6e985f20: 400 Bad Request`

`[scan-inspector][Error] Error while deleting Entry: Http failure response for https://locdb.bib.uni-mannheim.de/locdb-dev/bibliographicEntries/5bf42f664b39d61a6e985f36: 500 Internal Server Error`

Everytime I `save bounding box` I switch back to the "original" scan view. Is this intentional? Right now I have to save every edit on its own and therefore it is pretty annoying to switch back and forth between the scan views. Why can't I edit everything I want in one "session" and then save all the edits together?

**Comment by LauraErhard** [comment]
I just uploaded a fresh pdf and now I don't have any issues while deleting boxes.

**Comment by LauraErhard** [comment]
But we really need a way to save several boxes at the same, because this would save so much time and sometimes with narrow spaces I accidentally adjust the wrong box and then I have to cancel the whole process because I can't adjust the box I wanted to adjust in the first place.

**Comment by lgalke** [comment]
> But we really need a way to save several boxes at the same, because this would save so much time and sometimes with narrow spaces I accidentally adjust the wrong box and then I have to cancel the whole process because I can't adjust the box I wanted to adjust in the first place.

This should be possible, all boxes that have been changed are pushed to the back-end. What's your take on this @chah3d ? Maybe just a small problem with our view?

**Comment by LauraErhard** [comment]
Everytime I change more than one thing, the first box is saved and the other boxes are reset and I see this error:

**Comment by lgalke** [comment]
CC @anlausch could it be possible that we issue the requests too fast or something?

**Comment by chah3d** [comment]
It seems like only the first request is successful: 
selection_014

I have changed the requests to be sent asynchronously, to relieve the backend a little bit. But after the previous tests, none of the requests is successful. If sending one request at a time is still to much, the next request could be delayed a few 100 ms, so the waiting time would still be bearable for the user. 

selection_016

**Pull request merged**
